name = "TDAmapper"
uuid = "90314d98-8742-41ec-badb-bb392eb26b11"
authors = ["Guilherme Vituri <56522687+vituri@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetricSpaces = "737298cd-3e4b-40c4-a4ce-863151543a8d"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]

[compat]
julia = "1.9"
Clustering = "0.15"
Distances = "0.10"
Graphs = "1.8"
MetricSpaces = "0.0.1"
NearestNeighbors = "0.4"
ProgressMeter = "1.7"
Reexport = "1"
StatsBase = "0.33, 0.34"
TestItems = "1"
